/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Module.DAO.RegisteredEmployee;

/**
 *
 * @author William
 */
public class EmployeeList extends javax.swing.JPanel {

    public void setEmployeeList(Object[] employees) {
        this.lstEmployees.setListData(employees);
    }
    
    public RegisteredEmployee getRegisteredEmployeeSelected()    {
        return ((RegisteredEmployee)this.lstEmployees.getSelectedValue());
    }
    
    /**
     * Creates new form EmployeeListPanel
     */
    public EmployeeList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployees = new javax.swing.JList();
        label1 = new java.awt.Label();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(lstEmployees);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 230, 214));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("::Escolha um funcionário::");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 29));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JList lstEmployees;
    // End of variables declaration//GEN-END:variables
}
