/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Module.DAO.Availability;
import Module.DAO.AvailabilityDAO;
import Module.DAO.ConnectionSetup;
import Module.DAO.DoctorAppointmentDAO;
import Module.DAO.Patient;
import Module.DAO.PatientDAO;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amanda
 */
public class TelaMarcaConsulta extends javax.swing.JPanel {
    Patient pacienteAgendado;
    private Object Calendar;
    /**
     * Creates new form TelaMarcaConsulta
     */
    public TelaMarcaConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        labelMarcarConsul = new javax.swing.JLabel();
        lblExplicativoConsultas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDIas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstHorarios = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbPacientes = new javax.swing.JComboBox();
        lblPaciente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        labelMarcarConsul.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelMarcarConsul.setText(":: Marcar consulta ::");

        lblExplicativoConsultas.setText("Para marcar consultas lablabla");

        jScrollPane1.setViewportView(lstDIas);

        jScrollPane2.setViewportView(lstHorarios);

        jButton1.setText("Confirma");

        jButton2.setText("Cancelar");

        cmbPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPacientesActionPerformed(evt);
            }
        });

        lblPaciente.setText("Paciente:");

        jLabel1.setText("Selecione um dia");

        jLabel2.setText("<html>Horários disponíveis<br>Selecione e clique confirma</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(jButton2)
                            .addGap(67, 67, 67)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblPaciente))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cmbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExplicativoConsultas)
                            .addComponent(labelMarcarConsul))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelMarcarConsul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExplicativoConsultas)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente)
                    .addComponent(cmbPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("jLabel2");
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            // carregar lista de pacientes no combobox
            List<Patient> pacientes = new PatientDAO(ConnectionSetup.connection).listPatients();
            for(Patient p : pacientes) {
                this.cmbPacientes.addItem(p);
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(TelaMarcaConsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void cmbPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPacientesActionPerformed
        this.pacienteAgendado = (Patient) this.cmbPacientes.getSelectedItem();
    }//GEN-LAST:event_cmbPacientesActionPerformed

    /*
    public void regras() {
        //Pegando as horas ocupadas por uma data selecionada pelo paciente
                       DoctorAppointmentDAO doctorApp = new DoctorAppointmentDAO();
                       List<String> busyHours = doctorApp.SelectBusyHours(data);
                       
                       //Fazendo macumba pra pegar o dia da semana da data selecionada pelo usuario
                       Date date = Date.valueOf(data);
                       Calendar c = Calendar.getInstance();
                       c.setTime(date);
                       int dayOfWeek = c.get(Calendar.DAY_OF_WEEK);
                       
                       //Pegando as disponibilidades por um dia da semana da data selecionada, uma especialização e um medico se tiver sido selecionado
                       AvailabilityDAO avDAO = new AvailabilityDAO();
                       List<Availability> avs = avDAO.SelectAllAvailability(Integer.parseInt(session.getAttribute("idSpecialization").toString()), dayOfWeek, idhealthProfessionals);
                       //fazendo uma copia da lista para conseguir manipular a lista e rodar ela ao mesmo tempo
                       List<Availability> avscopy = avs;
                       
                       //tirando os horarios ocupados que ja tem consulta
                       for(String h : busyHours)
                           for(Availability av : avscopy)
                           {
                               if(h.equals(av.getIniciation().toString()))
                                   avs.remove(av);
                           }
    }
    */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbPacientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMarcarConsul;
    private javax.swing.JLabel lblExplicativoConsultas;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JList lstDIas;
    private javax.swing.JList lstHorarios;
    // End of variables declaration//GEN-END:variables
}
