package View.HealthProfessionals;

import Module.DBO.Availability;
import Module.DBO.ConnectionSetup;
import Module.DAO.AvailabilityDAO;
import Module.DAO.DoctorAppointmentDAO;
import Module.DAO.PatientDAO;
import Module.DBO.DoctorAppointment;
import Module.DBO.Patient;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class TelaMarcarConsulta_HealthProfessionals extends javax.swing.JPanel {

    private DoctorAppointmentDAO doctorAppointmentDAO = new DoctorAppointmentDAO(ConnectionSetup.connection);
    private PatientDAO patientDAO = new PatientDAO(ConnectionSetup.connection);
    private AvailabilityDAO availabilityDAO = new AvailabilityDAO(ConnectionSetup.connection);
    private DoctorAppointmentDAO doctorAppDAO = new DoctorAppointmentDAO(ConnectionSetup.connection);

    public TelaMarcarConsulta_HealthProfessionals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquisar = new javax.swing.JButton();
        txtNomePesquisado = new javax.swing.JTextField();
        lblData = new javax.swing.JLabel();
        btnConfimar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnDisponibilidade = new javax.swing.JButton();
        lblDisponibilidadeTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstHorarios = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPacientes = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        dateSelected = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        btnPesquisar.setText("...");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblData.setText("Data:");

        btnConfimar.setText("Confirmar");
        btnConfimar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnConfimar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnConfimar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnConfimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfimarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setMinimumSize(new java.awt.Dimension(200, 23));
        btnCancelar.setPreferredSize(new java.awt.Dimension(200, 23));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnDisponibilidade.setText("Disponibilidade");
        btnDisponibilidade.setMaximumSize(new java.awt.Dimension(200, 23));
        btnDisponibilidade.setMinimumSize(new java.awt.Dimension(200, 23));
        btnDisponibilidade.setPreferredSize(new java.awt.Dimension(200, 23));
        btnDisponibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisponibilidadeActionPerformed(evt);
            }
        });

        lblDisponibilidadeTitulo.setText("Horários disponíveis:");

        jScrollPane2.setViewportView(lstHorarios);

        jScrollPane1.setViewportView(lstPacientes);

        jLabel1.setText("Selecionar Paciente:");

        lblError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(":: Marcar Consulta ::");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnConfimar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtNomePesquisado))
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDisponibilidadeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(btnDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPesquisar))
                            .addComponent(dateSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnDisponibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblDisponibilidadeTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtNomePesquisado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfimar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        try {
            List<Patient> pacientes = this.patientDAO.SearchPatient(this.txtNomePesquisado.getText());
            this.lstPacientes.setListData(pacientes.toArray());
        } catch (Exception ex) {
            Logger.getLogger(TelaMarcarConsulta_HealthProfessionals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnConfimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfimarActionPerformed
        try {

            if (lstPacientes.getSelectedValue() == null) {
                this.lblError.setText("Selecione um paciente!");
            } else if (lstHorarios.getSelectedValue() == null) {
                this.lblError.setText("Selecione um horário!");
            } else {
                int idPatient = ((Patient) lstPacientes.getSelectedValue()).getId();
                int idAvailability = ((Availability) lstHorarios.getSelectedValue()).getId();

                String dateIniciation = ((Availability) lstHorarios.getSelectedValue()).getIniciation();
                String dateFinish = ((Availability) lstHorarios.getSelectedValue()).getFinish();

                dateIniciation = dateIniciation.substring(0, dateIniciation.length() - 11);
                dateFinish = dateFinish.substring(0, dateFinish.length() - 11);

                String date = getValidDate();

                //int idPatient, int idAvailability, Date dateIniciation, Date dateFinish
                DoctorAppointment doctorAppointment = new DoctorAppointment(idPatient, idAvailability, dateIniciation, dateFinish);
                if (this.doctorAppointmentDAO.InsertDoctorAppointment(doctorAppointment, date)) {
                    JOptionPane.showMessageDialog(this, "Consulta marcada!");
                    recarregarForm();
                } else {
                    recarregarForm();
                    this.lblError.setText("Erro ao tentar marcar consulta.");
                }
            }

        } catch (Exception ex) {
            this.lblError.setText("Erro ao tentar marcar consulta.");
        }
    }//GEN-LAST:event_btnConfimarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDisponibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilidadeActionPerformed
        try {
            carregarDisponibilidades();
        } catch (Exception ex) {
            Logger.getLogger(TelaMarcarConsulta_HealthProfessionals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDisponibilidadeActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        try {
            carregarPacientes();
        } catch (Exception ex) {
            Logger.getLogger(TelaMarcarConsulta_HealthProfessionals.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentAdded

    private void carregarPacientes() throws Exception {
        this.lblError.setText("");
        List<Patient> pacientes = this.patientDAO.SelectAllPatient();
        if (!pacientes.isEmpty()) {
            this.lstPacientes.setListData(pacientes.toArray());
        } else {
            this.lblError.setText("Não existe pacientes.");
        }
    }

    private void recarregarForm() throws Exception {
        this.lblError.setText("");
        carregarDisponibilidades();
    }

    private void carregarDisponibilidades() throws Exception {

        List<Availability> availabilities = new ArrayList<>();
        this.lstHorarios.setListData(availabilities.toArray());

        String date = getValidDate();
        int dayOfWeek = this.getDayOfWeek();
        availabilities = getValidAvailability(ConnectionSetup.id, dayOfWeek, date);
        if (!availabilities.isEmpty()) {
            this.lblError.setText("");
            this.lstHorarios.setListData(availabilities.toArray());
        } else {
            this.lblError.setText("Não foi encontrado disponibilidades para esse dia!");
        }
    }

    private List<Availability> getValidAvailability(int healthProfessionalID, int dayOfWeek, String data) throws Exception {

        List<Availability> availabilities = this.availabilityDAO.SelectAllAvailability(healthProfessionalID, dayOfWeek);
        List<Availability> avscopy = new ArrayList(availabilities);

        List<String> busyHours = this.doctorAppDAO.SelectBusyHours(data);

        for (String h : busyHours) {
            for (Availability av : avscopy) {
                String iniciation = av.getIniciation().substring(0, av.getIniciation().toString().length() - 8);
                if (h.equals(iniciation)) {
                    availabilities.remove(av);
                }
            }
        }

        return availabilities;
    }

    private String getValidDate() throws SQLException {
        Calendar c = this.dateSelected.getSelectedDate();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        //TODO: aqui verificar com a tabela holiday do bd
        String[] date = format.format(c.getTime()).split("-");
        String valid = this.doctorAppDAO.checkIfHoliday(Integer.parseInt(date[2]), Integer.parseInt(date[1]));
        if (valid.equals("ok")) {
            valid = format.format(c.getTime());
        } else {
            this.lblError.setText("<html>Não é possível agendar consultas neste dia!<br>Feriado de " + valid + "</html>");
            valid = null;
        }
        return valid;
    }

    private int getDayOfWeek() {
        Calendar c = this.dateSelected.getSelectedDate();
        return c.get(Calendar.DAY_OF_WEEK);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfimar;
    private javax.swing.JButton btnDisponibilidade;
    private javax.swing.JButton btnPesquisar;
    private datechooser.beans.DateChooserCombo dateSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDisponibilidadeTitulo;
    private javax.swing.JLabel lblError;
    private javax.swing.JList lstHorarios;
    private javax.swing.JList lstPacientes;
    private javax.swing.JTextField txtNomePesquisado;
    // End of variables declaration//GEN-END:variables
}
