/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Employee;

import Module.DBO.ConnectionSetup;
import Module.DAO.DoctorAppointmentDAO;
import Module.DAO.HealthProfessionalsDAO;
import Module.DBO.RegisteredEmployee;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author amanda
 */
public class TelaDesmarcarFrame extends javax.swing.JFrame {
    private DoctorAppointmentDAO docAppDAO;

    /**
     * Creates new form DesmarcarFramedeTeste
     */
    public TelaDesmarcarFrame() {
        initComponents();
        this.docAppDAO = new DoctorAppointmentDAO(ConnectionSetup.connection);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDesmarcar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstConsultas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        lblPaciente1 = new javax.swing.JLabel();
        cboMedico = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        btnDesmarcar.setText("Desmarcar");
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstConsultas);

        jLabel1.setText("Selecione um horário e clique em desmarcar para cancelar consulta:");

        lblPaciente1.setText("Médico:");

        cboMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboMedicoMouseClicked(evt);
            }
        });
        cboMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboMedico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDesmarcar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDesmarcar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarActionPerformed
        // TODO add your handling code here:
        if(lstConsultas.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Selecione um médico e uma consulta para desmarcar.");
        } else {
            try {
                String[] selected = lstConsultas.getSelectedValue().toString().split(", ");
                if(this.docAppDAO.unscheduleAppointment(Integer.parseInt(selected[0]))) {
                    JOptionPane.showMessageDialog(null, "Consulta desmarcada com sucesso!");
                    this.lstConsultas.removeAll();
                    loadConsultas(((RegisteredEmployee)cboMedico.getSelectedItem()).getId());
                } else {
                    JOptionPane.showMessageDialog(null, "Houve um problema ao desmarcar a consulta, por favor tente novamente.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TelaDesmarcarConsulta_Employee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDesmarcarActionPerformed

    private void cboMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboMedicoMouseClicked
    }//GEN-LAST:event_cboMedicoMouseClicked

    private void loadConsultas(int doctorId) {
        try {
            List<String> appointments = this.docAppDAO.selectSpecificDoctorAppointments(doctorId);
            if(!appointments.isEmpty()) {
                this.lstConsultas.setListData(appointments.toArray());
            } else {
                this.lstConsultas.removeAll();
                JOptionPane.showMessageDialog(null, "Médico não tem consultas agendadas.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TelaDesmarcarConsulta_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            List<RegisteredEmployee> doctors = new HealthProfessionalsDAO(ConnectionSetup.connection).listAllHealthProfessionals();
            for(RegisteredEmployee doctor : doctors) {
                cboMedico.addItem(doctor);
            }
        } catch (Exception ex) {
            Logger.getLogger(TelaDesmarcarConsulta_Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void cboMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicoActionPerformed
        // TODO add your handling code here:
        int doctorId = ((RegisteredEmployee)cboMedico.getSelectedItem()).getId();
        loadConsultas(doctorId);
    }//GEN-LAST:event_cboMedicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JComboBox cboMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPaciente1;
    private javax.swing.JList lstConsultas;
    // End of variables declaration//GEN-END:variables
}
