/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Employee;

import Module.Conexao.Controle;
import Module.DBO.ConnectionSetup;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Random;
import Module.DBO.RegisteredEmployee;
import Module.DBO.Employee;
import Module.DAO.RegisteredEmployeeDAO;
import Module.DBO.Role;
import Module.DAO.RoleDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 14432843
 */
public class TelaCadastroEmployee extends javax.swing.JPanel {

    private String login, senha, nome;
    private RegisteredEmployee registeredEmployee = null;
    private Employee employee = null;
    private RegisteredEmployeeDAO registeredEmployeeDAO = new RegisteredEmployeeDAO(ConnectionSetup.connection);
    private RoleDAO roleDAO = new RoleDAO(ConnectionSetup.connection);

    /**
     * Creates new form TelaCadastroEmployee
     */
    public TelaCadastroEmployee() {
        initComponents();

        //selecionando todo o texto do nome
        this.txtNome.requestFocus();

        //Desabilitando JTextFields de login e senha
        this.txtLogin.disable();
        this.txtSenha.disable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastro = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbbTipo = new javax.swing.JComboBox();
        lblNome1 = new javax.swing.JLabel();
        lblResultados = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCadastro.setText(":: Cadastro de Funcionário Administrativo ::");
        add(lblCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 328, -1));

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome completo");
        add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 250, -1));

        add(cbbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 250, -1));

        lblNome1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome1.setText("Cargo ");
        add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        lblResultados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResultados.setForeground(new java.awt.Color(102, 102, 102));
        lblResultados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblResultados.setText("_Resultados do Cadastro");
        add(lblResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 330, 40));

        lblLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLogin.setText("Login gerado");
        add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        lblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha.setText("Senha gerada");
        add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        txtLogin.setText("Nenhum login gerado");
        add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 230, -1));

        txtSenha.setText("Nenhuma senha gerada");
        add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 230, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 92, 31));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 92, 31));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if (txtNome.getText().isEmpty() || txtNome.getText() == null) {
            lblCadastro.setText("Digite seu nome :(");
            lblCadastro.setForeground(Color.red);
        } else {
            try {

                //vou gerar logins enquanto forem exclusivos
                this.geraLoginSenha();

                this.txtLogin.setText(this.login);
                this.txtSenha.setText(this.senha);
                this.nome = txtNome.getText();

                this.registeredEmployee = new RegisteredEmployee(nome, senha, login);
                int index = this.cbbTipo.getSelectedIndex();
                this.employee = new Employee(((Role) this.cbbTipo.getItemAt(index)).getId());

                //Inserindo no BD
                if (this.registeredEmployeeDAO.InsertEmployee(registeredEmployee, employee)) {
                    JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                    this.setVisible(false);
                } else {
                    lblCadastro.setText("Nao foi possivel criar cadastro.");
                    lblCadastro.setForeground(Color.red);
                }

            } catch (SQLException ex) {
                System.err.print("SQLException: " + ex.getMessage());
                System.err.println("SQLState: " + ex.getSQLState());
                System.err.println("VendorError: " + ex.getErrorCode());
            } catch (Exception e) {
                System.err.println("Erro desconhecido: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        try {
            for (Role role : roleDAO.SelectAllRole()) {
                this.cbbTipo.addItem(role);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentAdded

    private void geraLoginSenha() throws SQLException, Exception {

        //criando os vetores de login e senha de acordo com o tamanho dos caracteres
        char login[] = new char[Controle.NUM_CARACTERES_LOGIN.getValor()],
                senha[] = new char[Controle.NUM_CARACTERES_SENHA.getValor()];

        Random random = new Random();

        do {
            //:::::::::::::::::::::::::::::: LOGIN ::::::::::::::::::::::::::::::

            //adicionando os valores iniciais e finais [com base na tabela ASCII] aos inteiros
            int valorMinimo = Controle.ASCII_VALOR_MIN.getValor(),
                    valorMaximo = Controle.ASCII_VALOR_MAX.getValor();

            //atrelando os dois caracteres iniciais com o nome da pessoa
            login[0] = txtNome.getText().charAt(0);
            if (txtNome.getText().length() > 1) {
                login[1] = txtNome.getText().charAt(1);
            } else {
                login[1] = txtNome.getText().charAt(0);
            }

            //me baseando no valor do Enum para a parada do laço
            for (int i = 2; i < Controle.NUM_CARACTERES_LOGIN.getValor(); i++) {
                //atribuindo a cada posição do vetor um char, que será gerado randomicamente
                //entre os valores mínimos e máximos
                login[i] = (char) (valorMinimo + random.nextInt(valorMaximo - valorMinimo));
            }

            //:::::::::::::::::::::::::::::: SENHA ::::::::::::::::::::::::::::::
            //me baseando no valor do Enum para a parada do laço
            for (int i = 0; i < Controle.NUM_CARACTERES_SENHA.getValor(); i++) {
                //atribuindo a cada posição desse vetor um número aleatório (que vai até o 9), na base 10
                senha[i] = Character.forDigit(random.nextInt(9), 10);
            }

            //:::::::::::::::::::::::::::::: ATRIBUINDO VALORES ::::::::::::::::::::::::::::::
            //copyValueOf() transforma um vetor de chars em uma String :)
            this.login = String.copyValueOf(login);
            this.senha = String.copyValueOf(senha);

        } while (!this.registeredEmployeeDAO.IsUniqueLogin(this.login, this.senha));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox cbbTipo;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblResultados;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
