/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Employee;

import Module.DBO.ConnectionSetup;
import Module.DBO.Employee;
import Module.DAO.EmployeeDAO;
import Module.DBO.RegisteredEmployee;
import Module.DAO.RegisteredEmployeeDAO;
import Module.DBO.Role;
import Module.DAO.RoleDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 14432843
 */
public class TelaAlterarEmployee extends javax.swing.JPanel {

    private EmployeeDAO employeeDAO = new EmployeeDAO(ConnectionSetup.connection);
    private RoleDAO roleDAO = new RoleDAO(ConnectionSetup.connection);
    private RegisteredEmployeeDAO registeredEmployeeDAO = new RegisteredEmployeeDAO(ConnectionSetup.connection);

    /**
     * Creates new form TelaAlterarEmployee
     */
    public TelaAlterarEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomePesquisado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEmployees = new javax.swing.JList();
        btnPesquisar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        cbbTipo = new javax.swing.JComboBox();
        txtSenha = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setRequestFocusEnabled(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecionar Profissional:");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 165, 22));
        add(txtNomePesquisado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 230, 20));

        jScrollPane1.setViewportView(lstEmployees);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 290, 280));

        btnPesquisar.setText("Filtrar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 60, -1));

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome:");
        add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        lblLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLogin.setText("Login:");
        add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        lblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha.setText("Senha:");
        add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, -1));

        lblNome1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome1.setText("Tipo");
        add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 39, 22));

        add(cbbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 210, -1));
        add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 210, -1));
        add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 210, -1));
        add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 210, -1));

        btnVoltar.setText("Fechar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 102, 31));

        btnAlterar.setText("Alterar dados");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 100, 31));
        add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 394, -1, -1));
        lblError.getAccessibleContext().setAccessibleName("lblError");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText(":: Alterar cadastro de funcionário ::");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        try {
            List<RegisteredEmployee> registeredEmployees = this.employeeDAO.SearchEmployee(this.txtNomePesquisado.getText());
            this.lstEmployees.setListData(registeredEmployees.toArray());
        } catch (Exception ex) {
            Logger.getLogger(TelaAlterarEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            this.lblError.setText("");

            if (this.lstEmployees.getSelectedValue() == null) {
                this.lblError.setText("Não foi possivel alterar dados.");
            } else if (!hasError()) {
                int idRegisteredEmployee = ((RegisteredEmployee) this.lstEmployees.getSelectedValue()).getId();
                int idType = ((Role) this.cbbTipo.getSelectedItem()).getId();

                RegisteredEmployee registeredEmployee = new RegisteredEmployee(idRegisteredEmployee, this.txtNome.getText(), this.txtSenha.getText(), this.txtLogin.getText());
                Employee employee = new Employee(idType);

                if (registeredEmployeeDAO.UpdateEmployee(registeredEmployee, employee)) {
                    JOptionPane.showMessageDialog(null, "Perfil foi alterado com sucesso!");
                    carregarProfissionais();
                    //this.setVisible(false);
                } else {
                    this.lblError.setText("Não foi possivel alterar dados.");
                }
            } else {
                this.lblError.setText("Campos preenchidos incorretamente.");
            }

        } catch (Exception ex) {
            Logger.getLogger(TelaAlterarEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
        try {
            carregarRole();
            carregarProfissionais();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaCadastroEmployee.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentAdded

    private boolean hasError() {

        return this.txtNome.getText() == null || this.txtNome.getText().isEmpty()
                || this.txtSenha.getText() == null || this.txtSenha.getText().isEmpty()
                || this.txtLogin.getText() == null || this.txtLogin.getText().isEmpty();
    }

    private void carregarRole() throws Exception {
        for (Role role : this.roleDAO.SelectAllRole()) {
            this.cbbTipo.addItem(role);
        }
    }

    private void carregarProfissionais() throws Exception {
        List<RegisteredEmployee> registeredEmployees = this.employeeDAO.SelectAllEmployee();
        this.lstEmployees.setListData(registeredEmployees.toArray());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cbbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JList lstEmployees;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomePesquisado;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
